import type { Metadata } from "next";
import {  Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ThemeWrapper from "@/components/ThemeWrapper";

const plus = Plus_Jakarta_Sans({
  variable: "--font-plus",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Kanban Task Management Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plus.variable} antialiased`}
      >
        <ThemeWrapper>
      
      {children}
    </ThemeWrapper>
      </body>
    </html>
  );
}
